### ISSUE TITLE
No such file or directory exception

### ISSUE THREAD

**Issue by ghost** [macostea/cage#1]
Hi,
I can't run cage on Macos, zsh, Python 3.5. My steps was like on readme file except Python is in virtual environment:
1. pip install pycage
2. cd /tmp/application && touch test.py
3. cage app:create something

**Traceback:**

```
Traceback (most recent call last):
  File "/Users/psv/.env/qa-automation-web/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 595, in urlopen
    chunked=chunked)
  File "/Users/psv/.env/qa-automation-web/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 363, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1151, in _send_request
    self.endheaders(body)
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/Users/psv/.env/qa-automation-web/lib/python3.5/site-packages/docker/transport/unixconn.py", line 33, in connect
    sock.connect(self.unix_socket)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/psv/.env/qa-automation-web/lib/python3.5/site-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/Users/psv/.env/qa-automation-web/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 640, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/Users/psv/.env/qa-automation-web/lib/python3.5/site-packages/requests/packages/urllib3/util/retry.py", line 261, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/psv/.env/qa-automation-web/lib/python3.5/site-packages/requests/packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/Users/psv/.env/qa-automation-web/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 595, in urlopen
    chunked=chunked)
  File "/Users/psv/.env/qa-automation-web/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 363, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1151, in _send_request
    self.endheaders(body)
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/Users/psv/.env/qa-automation-web/lib/python3.5/site-packages/docker/transport/unixconn.py", line 33, in connect
    sock.connect(self.unix_socket)
requests.packages.urllib3.exceptions.ProtocolError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/psv/.env/qa-automation-web/bin/cage", line 11, in <module>
    sys.exit(main())
  File "/Users/psv/.env/qa-automation-web/lib/python3.5/site-packages/cage/__init__.py", line 25, in main
    handle_container_command(command_list[1], args)
  File "/Users/psv/.env/qa-automation-web/lib/python3.5/site-packages/cage/__init__.py", line 44, in handle_container_command
    res = container_handler.create_image(python_version)
  File "/Users/psv/.env/qa-automation-web/lib/python3.5/site-packages/cage/container/handler.py", line 75, in create_image
    response = self.__client.build(path=self.__app_path, tag=self.__image_name, rm=True)
  File "/Users/psv/.env/qa-automation-web/lib/python3.5/site-packages/docker/api/build.py", line 105, in build
    timeout=timeout,
  File "/Users/psv/.env/qa-automation-web/lib/python3.5/site-packages/docker/utils/decorators.py", line 47, in inner
    return f(self, *args, **kwargs)
  File "/Users/psv/.env/qa-automation-web/lib/python3.5/site-packages/docker/client.py", line 135, in _post
    return self.post(url, **self._set_request_timeout(kwargs))
  File "/Users/psv/.env/qa-automation-web/lib/python3.5/site-packages/requests/sessions.py", line 522, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/Users/psv/.env/qa-automation-web/lib/python3.5/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/psv/.env/qa-automation-web/lib/python3.5/site-packages/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/Users/psv/.env/qa-automation-web/lib/python3.5/site-packages/requests/adapters.py", line 473, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
```

**Comment by macostea** [comment]
Hi,

Thanks for reporting this!
This exception is thrown if Docker is not running.

I'll leave this issue open until I put in a better message.

**Comment by macostea** [comment]
Starting Docker before running any cage commands will fix this for now.

**Comment by ghost** [comment]
Thank you for reply! What do you mean "Docker is not running"?
Can you add some clear instructions about how to run Docker so cage could work too. Thanks!

```
psv@psv:/tmp|⇒  eval $(docker-machine env)
psv@psv:/tmp|⇒  docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
```

**Comment by macostea** [comment]
It seems you have the Docker Toolbox installed on your system.
Cage works with Docker for Mac as it uses the exposed socket to connect to the daemon.

I recommend you use Docker for Mac instead of the Toolbox as it also comes with some cool updates like not using VirtualBox for the containers.

See this page for more info:
https://docs.docker.com/docker-for-mac/docker-toolbox/

**Comment by macostea** [comment]
Closing this issue and added an Enhancement to specify the supported Docker versions in the README file: #2
